temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
library(data.table)
Electricdata <- read.table(unz(temp, "household_power_consumption.txt"),header=TRUE,sep=";",stringsAsFactors=FALSE)
Electricdata2<- subset(Electricdata, Electricdata$Date %in% c("1/2/2007", "2/2/2007"))
unlink(temp)
datesx <- strptime(paste(Electricdata2$Date,Electricdata2$Time,sep=" "),"%d/%m/%Y %H:%M:%S")
sub1 <- as.numeric(Electricdata2$Sub_metering_1)
sub2 <- as.numeric(Electricdata2$Sub_metering_2)
sub3 <- as.numeric(Electricdata2$Sub_metering_3)
activepowa <- as.numeric(Electricdata2$Global_active_power) 
Global_reactive_power <- as.numeric(Electricdata2$Global_reactive_power) 
Voltage <- as.numeric(Electricdata2$Voltage) 
par(mfrow=c(2,2))
plot(datesx,activepowa, type="l",xlab="", ylab="Global Active Power")
plot(datesx,Voltage, type="l",xlab="datetime", ylab="Voltage")
plot(datesx,sub1,ylim=range(c(sub1,sub2,sub3)), type="l",xlab="", ylab="Energy sub metering")
par(new=TRUE)
plot(datesx, sub2,ylim=range(c(sub1,sub2,sub3)), type = "l", axes = FALSE, bty = "n", xlab = "", ylab = "",col="red")
par(new=TRUE)
plot(datesx, sub3,ylim=range(c(sub1,sub2,sub3)), type = "l", axes = FALSE, bty = "n", xlab = "", ylab = "",col="blue")
legend("topright", lty=1,col= c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.50)
plot(datesx,Global_reactive_power, type="l",xlab="datetime", ylab="Global_reactive_power")
dev.copy(png,"plot4.png",width=725,height=725,units="px",res=100)
dev.off()
