temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
library(data.table)
Electricdata <- data.table(unz(temp, "household_power_consumption.txt"),sep=";")
Electricdata2<- subset(Electricdata, Electricdata$V1 %in% c("1/2/2007", "2/2/2007"))
unlink(temp)
hist(as.numeric(as.character(Electricdata2$V3)), col="red",main="Global Active Power",xlab="Global Active Power(kilowatts)")
dev.copy(png,"plot1.png",width=480,height=480,units="px",res=100)
dev.off()